name: prod-photoalbumservice

services:

  backend:
    image: fabricethutbbbaden/photoalbumservice-backend:latest
    container_name: backend
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      BACKEND_PORT: ${BACKEND_PORT}

      MYSQL_HOST:  ${MYSQL_ADDRESS}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

      STORAGE_PROVIDER: ${STORAGE_PROVIDER}
      BUCKET_NAME: ${BUCKET_NAME}
    ports:
      - "${BACKEND_PORT}:5038"
    restart: always