name: prod-photoalbumservice

services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${BACKEND_ADDRESS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    restart: always

  frontend:
    image: fabricethutbbbaden/photoalbumservice-frontend:latest
    container_name: frontend
    environment:
      BACKEND: ${BACKEND_ADDRESS}
      BACKEND_PORT: ${BACKEND_PORT}
      IMAGE_HOST: ${IMAGE_HOST}
      IMAGE_HOST_PORT: ${MINIO_PORT}
      BUCKET_NAME: ${BUCKET_NAME}
    ports:
      - "80:80"
    restart: always